package edu.poly.shop.common;

public enum PageType {
	PRODUCT_MANAGEMENT_PAGE,
	CATEGORY_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	SITE_HOME_PAGE,
	SITE_SHOPPINGCART_PAGE,
	SITE_LISTVIDEO_PAGE,
	STIE_WATCHVIDEO_PAGE,
	SITE_FAVORITEVIDEOS_PAGE, 
	FINDFAVORITEBYTITLE_PAGE,
}
